"""
Mosquitto password-file management.

Per-device MQTT credentials are generated by the pair flow and must be
registered with the broker before the device can connect. Mosquitto reads its
users from a password file; we share that file as a bind-mount with the
mosquitto container, append/remove rows here, and rely on the watcher in
mosquitto/init-passwd.sh to send SIGHUP and reload.

Hash format (mosquitto 2.0): `username:$7$<iter>$<b64_salt>$<b64_hash>`
where the hash is PBKDF2-HMAC-SHA512 over the password.
"""
from __future__ import annotations

import base64
import hashlib
import logging
import os
import secrets
import threading

log = logging.getLogger(__name__)

PASSWD_PATH = os.environ.get("MOSQUITTO_PASSWD_PATH", "/run/mosquitto/passwd")
ITERATIONS = 101  # mosquitto_passwd default for v2.0
SALT_BYTES = 12

_lock = threading.Lock()


def _hash(password: str) -> str:
    salt = secrets.token_bytes(SALT_BYTES)
    digest = hashlib.pbkdf2_hmac("sha512", password.encode(), salt, ITERATIONS, dklen=64)
    return f"$7${ITERATIONS}${base64.b64encode(salt).decode()}${base64.b64encode(digest).decode()}"


def _read_lines() -> list[str]:
    try:
        with open(PASSWD_PATH, "r") as f:
            return f.read().splitlines()
    except FileNotFoundError:
        return []


def _write_lines(lines: list[str]) -> None:
    # Atomic-ish write: temp file + rename keeps mosquitto from reading a
    # half-written file when SIGHUP fires. Same directory so rename is atomic.
    tmp = f"{PASSWD_PATH}.tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines))
        if lines:
            f.write("\n")
    os.replace(tmp, PASSWD_PATH)


def add_user(username: str, password: str) -> None:
    """Add or replace a user in the mosquitto password file."""
    entry = f"{username}:{_hash(password)}"
    with _lock:
        lines = _read_lines()
        kept = [ln for ln in lines if not ln.startswith(f"{username}:")]
        kept.append(entry)
        _write_lines(kept)
    log.info("mosquitto: registered user %s", username)


def remove_user(username: str) -> None:
    """Remove a user from the mosquitto password file. No-op if absent."""
    with _lock:
        lines = _read_lines()
        kept = [ln for ln in lines if not ln.startswith(f"{username}:")]
        if len(kept) == len(lines):
            return
        _write_lines(kept)
    log.info("mosquitto: removed user %s", username)
